package context

import (
	"fmt"
	"io"
	"strings"
)

// RenderFormat controls the output format of a context pack.
type RenderFormat string

const (
	FormatPack RenderFormat = "pack" // default: inline essentials, link references
	FormatRefs RenderFormat = "refs" // file path list only
)

// Render writes the context pack to w in the requested format.
func (p *Pack) Render(w io.Writer, format RenderFormat) error {
	switch format {
	case FormatPack:
		return p.renderPack(w)
	case FormatRefs:
		return p.renderRefs(w)
	default:
		return fmt.Errorf("unsupported render format %q", format)
	}
}

func (p *Pack) renderPack(w io.Writer) error {
	// Header
	fmt.Fprintf(w, "# Context Pack for %s/%s:%s\n\n", p.Flow, p.Command, p.Object)
	fmt.Fprintf(w, "Generated by specflowctl collect-context\n")
	fmt.Fprintf(w, "Flow: %s  Command: %s  Object: %s\n\n", p.Flow, p.Command, p.Object)

	// Separate essential and reference files
	var essential, reference []FileItem
	for _, f := range p.Files {
		if f.Essential {
			essential = append(essential, f)
		} else {
			reference = append(reference, f)
		}
	}

	// Core Truth section (essential files, inlined)
	if len(essential) > 0 {
		fmt.Fprintf(w, "## Core Truth\n\n")
		for _, f := range essential {
			if !f.Exists {
				fmt.Fprintf(w, "### %s (missing)\n\n", f.Path)
				continue
			}
			fmt.Fprintf(w, "### %s (%d lines)\n\n", f.Path, f.LineCount)
			fmt.Fprintf(w, "```markdown\n")
			io.WriteString(w, f.Content)
			if !strings.HasSuffix(f.Content, "\n") {
				io.WriteString(w, "\n")
			}
			fmt.Fprintf(w, "```\n\n")
		}
	}

	// References section (reference files, links only)
	if len(reference) > 0 {
		fmt.Fprintf(w, "## References (read if needed)\n\n")
		for _, f := range reference {
			label := ""
			if !f.Exists {
				label = " (missing)"
			}
			fmt.Fprintf(w, "- %s%s\n", f.Path, label)
		}
		fmt.Fprintf(w, "\n")
	}

	// Inventory
	fmt.Fprintf(w, "## Inventory\n\n")
	fmt.Fprintf(w, "%s\n", p.Inventory())

	return nil
}

func (p *Pack) renderRefs(w io.Writer) error {
	var essential, reference []FileItem
	for _, f := range p.Files {
		if f.Essential {
			essential = append(essential, f)
		} else {
			reference = append(reference, f)
		}
	}

	if len(essential) > 0 {
		fmt.Fprintf(w, "essential:\n")
		for _, f := range essential {
			if f.Exists {
				fmt.Fprintf(w, "  %s\n", f.Path)
			} else {
				fmt.Fprintf(w, "  %s (missing)\n", f.Path)
			}
		}
	}

	if len(reference) > 0 {
		fmt.Fprintf(w, "reference:\n")
		for _, f := range reference {
			label := ""
			if !f.Exists {
				label = " (missing)"
			}
			fmt.Fprintf(w, "  %s%s\n", f.Path, label)
		}
	}

	return nil
}
